// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/FocusFlowPromo.tsx": () => import("../components/mockups/FocusFlowPromo.tsx"),
  "./components/mockups/Screenshot1Home.tsx": () => import("../components/mockups/Screenshot1Home.tsx"),
  "./components/mockups/Screenshot2Focus.tsx": () => import("../components/mockups/Screenshot2Focus.tsx"),
  "./components/mockups/Screenshot3Blocked.tsx": () => import("../components/mockups/Screenshot3Blocked.tsx"),
  "./components/mockups/Screenshot4Stats.tsx": () => import("../components/mockups/Screenshot4Stats.tsx"),
  "./components/mockups/Screenshot5Permissions.tsx": () => import("../components/mockups/Screenshot5Permissions.tsx")
};
